### ISSUE TITLE
bug rabbit crash server

### ISSUE THREAD

**Issue by slema20** [yapzhenyie/GadgetsMenu#882] opened 2021-10-04 16:19 UTC
Describe the bug:
The bug basically crashes my server every time I try to equip the baby black and white rabbit.

Server Version: [1.17.1]
GadgetsMenu Version: [5.0.7]

I use spigot and I won't use paper

Time: 4/10/21 18:07
Description: Ticking entity

java.lang.IllegalAccessError: Clase com/yapzhenyie/GadgetsMenu/nms/v1_17_R1/pets/entity/types/EntityRabbitPet$ControllerMoveRabbit accediendo de forma no permitida al miembro "protected" de la clase net/minecraft/world/entity/EntityLiving
	at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.types.EntityRabbitPet$ControllerMoveRabbit.a(EntityRabbitPet.java:177)
	at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:817)
	at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3079)
	at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:608)
	at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.types.EntityRabbitPet.movementTick(EntityRabbitPet.java:126)
	at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2808)
	at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:376)
	at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.EntityPet.tick(EntityPet.java:261)
	at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815)
	at net.minecraft.server.level.WorldServer$$Lambda$7346/0x00000000110b9240.accept(Unknown Source)
	at net.minecraft.world.level.World.a(World.java:697)
	at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527)
	at net.minecraft.server.level.WorldServer$$Lambda$7345/0x0000000010c1b1f0.accept(Unknown Source)
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54)
	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1299)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
	at net.minecraft.server.MinecraftServer$$Lambda$3896/0x00000000118aab78.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:853)

**Comment by yapzhenyie** [comment] 2021-10-05 13:17
This issue only happen for spigot server. Let me see what I can do to fix the issue for spigot server.

**Comment by yapzhenyie** [comment] 2021-10-05 13:18
Duplicate of #877

**Comment by yapzhenyie** [comment] 2021-12-24 14:19
This issue has been fixed. Please check for the new update.

**Closed by yapzhenyie** 2021-12-24 14:19 UTC
Labels: Type: Bug, Status: Resolved
