### ISSUE TITLE
Asynchronous entity ticklist removal java.lang.Throwable: null

### ISSUE THREAD

**Issue by DarkyCat** [yapzhenyie/GadgetsMenu#871] opened 2021-08-15 14:01 UTC
**Describe the bug**

**To Reproduce**
https://mcpaste.io/42ffdc62264c875a
https://mcpaste.io/dbdaf22da38e346b [5.0.4]

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: [1.17.1]
 - GadgetsMenu Version: [5.0.5 and 5.0.4]
 - Console stack trace if have.

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment] 2021-08-15 14:22
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment] 2021-08-15 14:22
This issue has been fixed. Please check for the new update and keep me posted if the issue is fixed.

**Comment by DarkyCat** [comment] 2021-08-15 14:36
Yes it is fixed (Spiderman suit)

**Comment by DarkyCat** [comment] 2021-08-15 14:36
https://mcpaste.io/42ffdc62264c875a - I still do not understand why this error occurred

**Comment by DarkyCat** [comment] 2021-08-18 10:45
After the 5.0.6 update, it disappeared

**Closed** 2021-08-23 09:20 UTC
Labels: Type: Bug, Status: Resolved
