### ISSUE TITLE
 Consle spam causes by latest protocollib 

### ISSUE THREAD

**Issue by CloudeLecaw** [yapzhenyie/GadgetsMenu#927] opened 2022-07-29 07:20 UTC
the latest version causes a massive console spam.
may because some packets changed in protocollib (Build 580+)
On spigot the latest version (Build 583) is recomment to use for 1.19 Servers

here the log from console.
https://pastebin.com/iicUxBFD

**Comment by yapzhenyie** [comment] 2022-07-29 15:39
Please wait for newer update.

**Comment by yapzhenyie** [comment] 2022-07-29 15:41
Duplicate of #926

**Comment by yapzhenyie** [comment] 2022-07-31 15:08
This issue has been fixed. Please check for the new update.

**Closed by yapzhenyie** 2022-07-31 15:08 UTC
Labels: Type: Bug, Status: Resolved
